swagger: "2.0"
info:
  title: Kadaya Backend API Documentation
  version: 1.0.0
host: localhost:3000
schemes:
  - http
tags:
  - name: Shop
    description: Shop
  - name: Buyer
    description: Buyer
  - name: Category
    description: Category
  - name: Image
    description: Image
  - name: Item
    description: Item
  - name: Monitoring
    description: Monitoring
  - name: Order
    description: Order
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: x-access-token
paths:
  /image/{key}:
    get:
      summary: Get image by key
      tags:
        - Image
      consumes:
        - application/json
      produces:
        - image/jpg
        - application/json
      parameters:
        - name: key
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK
        502:
          description: Server Error
  /image/shop/{shop_id}/keys:
    get:
      summary: Get all the images' keys for a shop
      tags:
        - Image
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: shop_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK
        502:
          description: Server Error
  /image/shop/{shop_id}/:
    post:
      summary: upload image/images
      tags:
        - Image
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: shop_id
          in: path
          required: true
          type: string
        - name: image
          type: file
          required: true
          in: formData
      responses:
        200:
          description: OK
        502:
          description: Server Error

