swagger: "2.0"
info:
  title: Kadaya Backend API Documentation
  version: 1.0.0
host: localhost:3000
schemes:
  - http
tags:
  - name: Shop
    description: Shop
  - name: Buyer
    description: Buyer
  - name: Category
    description: Category
  - name: Image
    description: Image
  - name: Item
    description: Item
  - name: Monitoring
    description: Monitoring
  - name: Order
    description: Order
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: x-access-token
paths:
  /update/:
    post:
      summary: should app update
      tags:
        - Update
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: json body
          schema:
            type: object
            required:
              - version
            properties:
              version:
                type: string
                example: 0.2.3
      responses:
        201:
          description: Updated
        400:
          description: Not Found
        502:
          description: Server Error